### ISSUE TITLE
Could link to Github repo with Github icon

### ISSUE THREAD

**Issue by ThePrez** [Club-Seiden/ibm-i-clock#11]
in case folks have more information to add

**Comment by jbh** [comment]
What do you think about having a [Github Ribbon](https://github.com/blog/273-github-ribbons)?

**Comment by ThePrez** [comment]
Works for me, assuming it is non-intrusive on the page

**Comment by alanseiden** [comment]
Excellent. I was thinking the site would benefit from being more interactive, drawing people in to our IBMiOSS community. The ribbon may do the trick (?).
